/* eslint-disable arrow-body-style */
import { chakra } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <chakra.div>
      <Head>
        <title>Vendor Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <chakra.div>Welcome to the Shop Urban Vendor app. Coming soon...</chakra.div>
    </chakra.div>
  )
}

export default Home
