/* eslint-disable arrow-body-style */
import { chakra } from '@chakra-ui/react'
import DesktopView from '@components/Dashboard/Desktop'
import MobileView from '@components/Dashboard/Mobile'
import VendorDashBoardLayout from '@components/Layout/VendorDashBoardLayout'
import type { NextPage } from 'next'
import Head from 'next/head'

const VendorDashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>Vendor Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VendorDashBoardLayout>
      <chakra.div display={{ base: "none", xl: "block" }}>
        <DesktopView />
      </chakra.div>
      <chakra.div display={{ base: "block", xl: "none" }}>
        <MobileView />
      </chakra.div>
    </VendorDashBoardLayout>
    </>
  )
}

export default VendorDashboard
