/* eslint-disable arrow-body-style */
import { chakra } from '@chakra-ui/react'
import VendorDashBoardLayout from '@components/Layout/VendorDashBoardLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const VendorDashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>Vendor Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VendorDashBoardLayout>
        <chakra.div>Welcome to the Shop Urban Vendor app. Coming soon... <Link href="/indexa">Hi</Link></chakra.div>
      </VendorDashBoardLayout>
    </>
  )
}

export default VendorDashboard
